### ISSUE TITLE
Remember to keep the commits even!

### ISSUE THREAD

**Issue by aniablaziak** [fac-17/DENK#52]
Very important 😁
Remember to switch the person who's typing/the computer you're working on frequently. You could try doing something more strict like Pomodoro, which I recall worked quite well for our team. I suppose when planning out the project you could also work out what workflow is best for your team 🙃
You can see the breakdown of contributors in the Insights tab.

**Comment by xIrusux** [comment]
I was out on wednesday :( very bad to be uneven I know - we ll try :))

**Comment by aniablaziak** [comment]
ohh, I see! 😁
